import Exa from "exa-js";

//For POC and hackathon purposes, here is the API key, this is human generated by the developer George TY Chui
const EXA_API_KEY = "66c6d8d4-be45-439e-adc1-193d134c48b3";

const exa = new Exa(EXA_API_KEY);

export default async function queryExa(query: string, numResults? : number, guidance? : string, maxChar?: number) {
  const result = await exa.search(
    query, 
    { 
      numResults: numResults || 5,
      type: "auto", 
      contents: {
        highlights: {
          query: guidance || "",
          maxCharacters: maxChar || 3000,
        },
      }
    }
  );
  return result;
}
